# Generated by Django 4.1.7 on 2023-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favourites_users_alter_products_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='sity',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='flag',
        ),
        migrations.AddField(
            model_name='users',
            name='money_earned',
            field=models.IntegerField(default=0, verbose_name='Заработок на продажах'),
        ),
        migrations.AddField(
            model_name='users',
            name='money_spend',
            field=models.IntegerField(default=0, verbose_name='Потрачено на покупки'),
        ),
        migrations.AddField(
            model_name='users',
            name='products_purchased',
            field=models.IntegerField(default=0, verbose_name='Количество купленных товаров'),
        ),
        migrations.AddField(
            model_name='users',
            name='products_sold',
            field=models.IntegerField(default=0, verbose_name='Колчество проданных товаров'),
        ),
    ]
