# Generated by Django 4.1.5 on 2023-03-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favourites_users_alter_products_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(auto_created='', default='', max_length=25, verbose_name='Имя'),
        ),
    ]
