# Generated by Django 4.1.7 on 2023-03-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_sity_users_city_remove_users_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=-1, verbose_name='Возраст'),
        ),
    ]
