# Generated by Django 4.1.5 on 2023-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='', max_length=25, verbose_name='Имя'),
        ),
    ]
