# Generated by Django 4.1.7 on 2023-03-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_users_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img_link',
            field=models.TextField(default='', verbose_name='Ссылка на изображение для аватарки'),
        ),
    ]
