# Generated by Django 4.1.7 on 2023-03-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_users_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='users',
            name='img_link',
            field=models.TextField(blank=True, default='', verbose_name='Ссылка на изображение для аватарки'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_surname',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Фамилия'),
        ),
    ]
