# Generated by Django 4.1.5 on 2023-03-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_users_flag_remove_users_sity_users_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img_link',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='Ссылка на изображение для аватарки'),
        ),
    ]
