# Generated by Django 4.1.5 on 2023-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_users_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='count',
        ),
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество товара (в шк)'),
        ),
    ]
