# Generated by Django 4.1.5 on 2023-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_users_count_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.CharField(default='Red Catalog', max_length=40, verbose_name='Продавец'),
        ),
    ]
