# Generated by Django 4.1.5 on 2023-03-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_products_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='ID пользователя')),
                ('id_product', models.IntegerField(verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'Карзины',
                'verbose_name_plural': 'Карзины',
            },
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='ID пользователя')),
                ('id_product', models.IntegerField(verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'Купленное',
                'verbose_name_plural': 'Купленное',
            },
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='ID пользователя')),
                ('id_product', models.IntegerField(verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'Проданное',
                'verbose_name_plural': 'Проданное',
            },
        ),
    ]
