# Generated by Django 4.1.5 on 2023-04-08 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_card_purchased_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Корзины', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AddField(
            model_name='purchased',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время покупки'),
        ),
    ]
